// Account Register
export const REQUEST_REGISTER_NEW_ACCOUNT = 'REQUEST_REGISTER_NEW_ACCOUNT'
export const REQUEST_REGISTER_NEW_ACCOUNT_SUCCESS = 'REQUEST_REGISTER_NEW_ACCOUNT_SUCCESS'
export const REQUEST_REGISTER_NEW_ACCOUNT_FAIL = 'REQUEST_REGISTER_NEW_ACCOUNT_FAIL'

// Account login
export const REQUEST_ACCOUNT_LOGIN = 'REQUEST_REGISTER_NEW_ACCOUNT'
export const REQUEST_ACCOUNT_LOGIN_SUCCESS = 'REQUEST_ACCOUNT_LOGIN_SUCCESS'
export const REQUEST_ACCOUNT_LOGIN_FAIL = 'REQUEST_ACCOUNT_LOGIN_FAIL'

// Account logout
export const REQUEST_ACCOUNT_LOGOUT = 'REQUEST_ACCOUNT_LOGOUT'
export const REQUEST_ACCOUNT_LOGOUT_SUCCESS = 'REQUEST_ACCOUNT_LOGOUT_SUCCESS'
export const REQUEST_ACCOUNT_LOGOUT_FAIL = 'REQUEST_ACCOUNT_LOGOUT_FAIL'