// Sample action types
export const REQUEST_ADD_NEW_SAMPLE = 'REQUEST_ADD_NEW_SAMPLE'
export const REQUEST_ADD_NEW_SAMPLE_SUCCESS = 'REQUEST_ADD_NEW_SAMPLE_SUCCESS'
export const REQUEST_ADD_NEW_SAMPLE_FAIL = 'REQUEST_ADD_NEW_SAMPLE_FAIL'
