// Create new sample action types
export const REQUEST_ADD_NEW_SAMPLE = 'REQUEST_ADD_NEW_SAMPLE'
export const REQUEST_ADD_NEW_SAMPLE_SUCCESS = 'REQUEST_ADD_NEW_SAMPLE_SUCCESS'
export const REQUEST_ADD_NEW_SAMPLE_FAIL = 'REQUEST_ADD_NEW_SAMPLE_FAIL'

// Sample action types
export const REQUEST_GET_ALL_NAMES_OF_SAMPLES = 'REQUEST_GET_ALL_NAMES_OF_SAMPLES'
export const REQUEST_GET_ALL_NAMES_OF_SAMPLES_SUCCESS = 'REQUEST_GET_ALL_NAMES_OF_SAMPLES_SUCCESS'
export const REQUEST_GET_ALL_NAMES_OF_SAMPLES_FAIL = 'REQUEST_GET_ALL_NAMES_OF_SAMPLES_FAIL'

export const REQUEST_GET_ALL_EXISTING_TAGS = 'REQUEST_GET_ALL_EXISTING_TAGS'
export const REQUEST_GET_ALL_EXISTING_TAGS_SUCCESS = 'REQUEST_GET_ALL_EXISTING_TAGS_SUCCESS'
export const REQUEST_GET_ALL_EXISTING_TAGS_FAIL = 'REQUEST_GET_ALL_EXISTING_TAGS_FAIL'