// Sample action types
export const REQUEST_ADD_NEW_SAMPLE = 'REQUEST_ADD_NEW_SAMPLE'
export const REQUEST_ADD_NEW_SAMPLE_SUCCESS = 'REQUEST_ADD_NEW_SAMPLE_SUCCESS'
export const REQUEST_ADD_NEW_SAMPLE_FAIL = 'REQUEST_ADD_NEW_SAMPLE_FAIL'

// Counter action types
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';

// Forecast action types
export const REQUEST_WEATHER_FORECASTS = 'REQUEST_WEATHER_FORECASTS';
export const RECEIVE_WEATHER_FORECASTS = 'RECEIVE_WEATHER_FORECASTS';
