// Notification Message action types
export const SET_INFO_NOTIFICATION_MESSAGE = "SET_INFO_NOTIFICATION_MESSAGE"
export const CLEAR_INFO_NOTIFICATION_MESSAGE = "CLEAR_INFO_NOTIFICATION_MESSAGE"

export const SET_SUCCESSFUL_NOTIFICATION_MESSAGE = "SET_SUCCESSFUL_NOTIFICATION_MESSAGE"
export const CLEAR_SUCCESSFUL_NOTIFICATION_MESSAGE = "CLEAR_SUCCESSFUL_NOTIFICATION_MESSAGE"

export const SET_ERROR_NOTIFICATION_MESSAGE = "SET_ERROR_NOTIFICATION_MESSAGE"
export const CLEAR_ERROR_NOTIFICATION_MESSAGE = "CLEAR_ERROR_NOTIFICATION_MESSAGE"
