// InfoMessage action types
export const SET_INFO_MESSAGE_BOX = "SET_INFO_MESSAGE_BOX"
export const SET_SUCCESSFUL_MESSAGE_BOX = "SET_SUCCESSFUL_MESSAGE_BOX"
export const SET_ERROR_MESSAGE_BOX = "SET_ERROR_MESSAGE_BOX"
export const CLEAR_INFO_MESSAGE_BOX = "CLEAR_INFO_MESSAGE_BOX"