// CreateNewSample action types
export const REQUEST_ADD_NEW_SAMPLE = 'REQUEST_ADD_NEW_SAMPLE'
export const REQUEST_ADD_NEW_SAMPLE_SUCCESS = 'REQUEST_ADD_NEW_SAMPLE_SUCCESS'
export const REQUEST_ADD_NEW_SAMPLE_FAIL = 'REQUEST_ADD_NEW_SAMPLE_FAIL'

// DetailedSample action types
export const REQUEST_GET_DETAILED_SAMPLE = 'REQUEST_GET_DETAILED_SAMPLE'
export const REQUEST_GET_DETAILED_SAMPLE_SUCCESS = 'REQUEST_GET_DETAILED_SAMPLE_SUCCESS'
export const REQUEST_GET_DETAILED_SAMPLE_FAIL = 'REQUEST_GET_DETAILED_SAMPLE_FAIL'

// Find sample by givern search params
export const FETCH_SAMPLE_BY_GIVEN_SEARCH_PARAMETERS = 'FETCH_SAMPLE_BY_GIVEN_SEARCH_PARAMETERS'
export const FETCH_SAMPLE_BY_GIVEN_SEARCH_PARAMETERS_SUCCESS = 'FETCH_SAMPLE_BY_GIVEN_SEARCH_PARAMETERS_SUCCESS'
export const FETCH_SAMPLE_BY_GIVEN_SEARCH_PARAMETERS_FAIL = 'FETCH_SAMPLE_BY_GIVEN_SEARCH_PARAMETERS_FAIL'